### PR TITLE
Add English quest data

### PR DESCRIPTION
**Pull request by Sharlikran**
I do not have a way to get the translations of all the NPC and Quest names. Will you guys be able to handle that?

### CODE REVIEW

**Comment by Sharlikran** [comment]
None of that data is auto generated with other creative means. It is collected with Destinations and extracted with `Destinations Extractor.exe`

**Comment by Sharlikran** [comment]
Fiddle I didn't wan the commit https://github.com/ESOUIMods/Destinations/commit/24676aa980ae7d5ee95c89d514440108a476f81f included. Oh well.

Would you kindly leave the comments there?

The reason is that currently in Elsweyr and also in Greymoor, there will be map names with a `.base` instead of `_base` and I do not know if you account for that or not. If you do not then that needs updating and it is beyond my understanding of Lua and the Destinations code base.

**Comment by Sharlikran** [comment]
I am sorry if my PM on ESOUI wasn't very concise but I don't know how to explain everything. I will attempt to ask the question a little better. Again I wasn't trying to be rude or disrespectful.

```lua
["DQD: rimmen_base_0.dds/0"] = "rimmen_base_0.dds{0.7770, 0.3679,\\t\\dqJode's Core\\dq,\\t81010,\\t0,\\t0,\\t0,\\t10000,\\t10000,\\t0},",
```

Using LibPGS applies post processing to the coordinates such that `xpos= 0.1849195659, ypos = 0.4480309784,` from `GetMapPlayerPosition()` would be `x = 0.0451987986, y = 0.7245392147,`.

What I was trying to ask was are the x,y coordinates raw data from using `GetMapPlayerPosition("player")` or is there any pre or post processing that Destinations does?

**Comment by Sharlikran** [comment]
```lua
local function FormatCoords(number)
    return ("%05.04f"):format(zo_round(number * 10000)/10000)
end
```
I found it, you just round it off to the 4th place. Well that makes things easier.

**Comment by LennartPiro** [comment]
Hi, I'm sorry for being so slow to reply. I'm busy at work and will check your data on the weekend, to get an update out for when the expansion launches.

Yes, the x,y numbers are just the GetMapPlayerPosition. Rounding is optional, 4 digits is usually enough. I've actually never seen the FormatCoords function you just quoted, it's something the original author must have written :D 

Thanks again for helping with the addon!

**Comment by Sharlikran** [comment]
I might be able to get more information and well, certainly more Quest names. I was able to obtain some names in French, German, and Japanese. I just haven't had time yet to do a rebase and double check everything. I'll let you know when I'm done. Plus because the default setting for recording quests with Destinations always defaults to OFF then I lost a bunch of quest data that I could have used with destinations.
 
However I think I can convert some of the new data to work using that function that I found.

**Comment by Sharlikran** [comment]
@LennartPiro I have to put most of this on hold for now. While I was trying to come up with a way to synchronize all the quest names so that players using Destinations opened the map and saw a quest pin would have some kind of name for the tooltip. I made some functions to loop over things.

Then after I did that I felt I should do the same for the quest pin locations. So I started making functions to loop over all of that.

After that I wanted to find some way to use the data for either Quest Map or Destinations. That's when everything started to explode and get frustrating.

So now I have the beginnings of a new Library for quest information. I have to get some sleep but tomorrow I am going to try and use the Library for just Quest Names and Quest Givers (NPCs) and see how well it works.

Then see how to make the other functions I need. So it will take a while before I have a working change that would be usable.

**Comment by Sharlikran** [comment]
I realized I probably should not use master for the changes. So I have rebased the branch. I will open a new pull request using [dev-shar](https://github.com/ESOUIMods/Destinations/tree/dev-shar) when I have made more changes and after more testing.

**Pull request closed without merging**
